version: '3'

services:
  authentication_service:
    container_name: authentication_service
    build:
      context: ./authentication
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=$MONGO_HOSTNAME
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "8080:8080"
    networks:
      - app-network
    
  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - bd_authentication:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  bd_authentication:
    driver: local
    driver_opts:
      type: none
      device: /home/lucas/bd/authentication
      o: bind